/* 
 * ToDo API
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Orders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrdersTests
    {
        // TODO uncomment below to declare an instance variable for Orders
        //private Orders instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Orders
            //instance = new Orders();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Orders
        /// </summary>
        [Test]
        public void OrdersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Orders
            //Assert.IsInstanceOfType<Orders> (instance, "variable 'instance' is a Orders");
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'EmployeeId'
        /// </summary>
        [Test]
        public void EmployeeIdTest()
        {
            // TODO unit test for the property 'EmployeeId'
        }
        /// <summary>
        /// Test the property 'OrderDate'
        /// </summary>
        [Test]
        public void OrderDateTest()
        {
            // TODO unit test for the property 'OrderDate'
        }
        /// <summary>
        /// Test the property 'RequiredDate'
        /// </summary>
        [Test]
        public void RequiredDateTest()
        {
            // TODO unit test for the property 'RequiredDate'
        }
        /// <summary>
        /// Test the property 'ShippedDate'
        /// </summary>
        [Test]
        public void ShippedDateTest()
        {
            // TODO unit test for the property 'ShippedDate'
        }
        /// <summary>
        /// Test the property 'ShipVia'
        /// </summary>
        [Test]
        public void ShipViaTest()
        {
            // TODO unit test for the property 'ShipVia'
        }
        /// <summary>
        /// Test the property 'Freight'
        /// </summary>
        [Test]
        public void FreightTest()
        {
            // TODO unit test for the property 'Freight'
        }
        /// <summary>
        /// Test the property 'ShipName'
        /// </summary>
        [Test]
        public void ShipNameTest()
        {
            // TODO unit test for the property 'ShipName'
        }
        /// <summary>
        /// Test the property 'ShipAddress'
        /// </summary>
        [Test]
        public void ShipAddressTest()
        {
            // TODO unit test for the property 'ShipAddress'
        }
        /// <summary>
        /// Test the property 'ShipCity'
        /// </summary>
        [Test]
        public void ShipCityTest()
        {
            // TODO unit test for the property 'ShipCity'
        }
        /// <summary>
        /// Test the property 'ShipRegion'
        /// </summary>
        [Test]
        public void ShipRegionTest()
        {
            // TODO unit test for the property 'ShipRegion'
        }
        /// <summary>
        /// Test the property 'ShipPostalCode'
        /// </summary>
        [Test]
        public void ShipPostalCodeTest()
        {
            // TODO unit test for the property 'ShipPostalCode'
        }
        /// <summary>
        /// Test the property 'ShipCountry'
        /// </summary>
        [Test]
        public void ShipCountryTest()
        {
            // TODO unit test for the property 'ShipCountry'
        }
        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Test]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
        /// <summary>
        /// Test the property 'Employee'
        /// </summary>
        [Test]
        public void EmployeeTest()
        {
            // TODO unit test for the property 'Employee'
        }
        /// <summary>
        /// Test the property 'ShipViaNavigation'
        /// </summary>
        [Test]
        public void ShipViaNavigationTest()
        {
            // TODO unit test for the property 'ShipViaNavigation'
        }
        /// <summary>
        /// Test the property 'OrderDetails'
        /// </summary>
        [Test]
        public void OrderDetailsTest()
        {
            // TODO unit test for the property 'OrderDetails'
        }

    }

}
