/* 
 * ToDo API
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Region
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegionTests
    {
        // TODO uncomment below to declare an instance variable for Region
        //private Region instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Region
            //instance = new Region();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Region
        /// </summary>
        [Test]
        public void RegionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Region
            //Assert.IsInstanceOfType<Region> (instance, "variable 'instance' is a Region");
        }


        /// <summary>
        /// Test the property 'RegionId'
        /// </summary>
        [Test]
        public void RegionIdTest()
        {
            // TODO unit test for the property 'RegionId'
        }
        /// <summary>
        /// Test the property 'RegionDescription'
        /// </summary>
        [Test]
        public void RegionDescriptionTest()
        {
            // TODO unit test for the property 'RegionDescription'
        }
        /// <summary>
        /// Test the property 'Territories'
        /// </summary>
        [Test]
        public void TerritoriesTest()
        {
            // TODO unit test for the property 'Territories'
        }

    }

}
