/* 
 * ToDo API
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Shippers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShippersTests
    {
        // TODO uncomment below to declare an instance variable for Shippers
        //private Shippers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Shippers
            //instance = new Shippers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Shippers
        /// </summary>
        [Test]
        public void ShippersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Shippers
            //Assert.IsInstanceOfType<Shippers> (instance, "variable 'instance' is a Shippers");
        }


        /// <summary>
        /// Test the property 'ShipperId'
        /// </summary>
        [Test]
        public void ShipperIdTest()
        {
            // TODO unit test for the property 'ShipperId'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Orders'
        /// </summary>
        [Test]
        public void OrdersTest()
        {
            // TODO unit test for the property 'Orders'
        }

    }

}
