/* 
 * ToDo API
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomerCustomerDemo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerCustomerDemoTests
    {
        // TODO uncomment below to declare an instance variable for CustomerCustomerDemo
        //private CustomerCustomerDemo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomerCustomerDemo
            //instance = new CustomerCustomerDemo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomerCustomerDemo
        /// </summary>
        [Test]
        public void CustomerCustomerDemoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomerCustomerDemo
            //Assert.IsInstanceOfType<CustomerCustomerDemo> (instance, "variable 'instance' is a CustomerCustomerDemo");
        }


        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'CustomerTypeId'
        /// </summary>
        [Test]
        public void CustomerTypeIdTest()
        {
            // TODO unit test for the property 'CustomerTypeId'
        }
        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Test]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
        /// <summary>
        /// Test the property 'CustomerType'
        /// </summary>
        [Test]
        public void CustomerTypeTest()
        {
            // TODO unit test for the property 'CustomerType'
        }

    }

}
