/* 
 * ToDo API
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Employees
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmployeesTests
    {
        // TODO uncomment below to declare an instance variable for Employees
        //private Employees instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Employees
            //instance = new Employees();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Employees
        /// </summary>
        [Test]
        public void EmployeesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Employees
            //Assert.IsInstanceOfType<Employees> (instance, "variable 'instance' is a Employees");
        }


        /// <summary>
        /// Test the property 'EmployeeId'
        /// </summary>
        [Test]
        public void EmployeeIdTest()
        {
            // TODO unit test for the property 'EmployeeId'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'TitleOfCourtesy'
        /// </summary>
        [Test]
        public void TitleOfCourtesyTest()
        {
            // TODO unit test for the property 'TitleOfCourtesy'
        }
        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Test]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }
        /// <summary>
        /// Test the property 'HireDate'
        /// </summary>
        [Test]
        public void HireDateTest()
        {
            // TODO unit test for the property 'HireDate'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'HomePhone'
        /// </summary>
        [Test]
        public void HomePhoneTest()
        {
            // TODO unit test for the property 'HomePhone'
        }
        /// <summary>
        /// Test the property 'Extension'
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO unit test for the property 'Extension'
        }
        /// <summary>
        /// Test the property 'Photo'
        /// </summary>
        [Test]
        public void PhotoTest()
        {
            // TODO unit test for the property 'Photo'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'ReportsTo'
        /// </summary>
        [Test]
        public void ReportsToTest()
        {
            // TODO unit test for the property 'ReportsTo'
        }
        /// <summary>
        /// Test the property 'PhotoPath'
        /// </summary>
        [Test]
        public void PhotoPathTest()
        {
            // TODO unit test for the property 'PhotoPath'
        }
        /// <summary>
        /// Test the property 'ReportsToNavigation'
        /// </summary>
        [Test]
        public void ReportsToNavigationTest()
        {
            // TODO unit test for the property 'ReportsToNavigation'
        }
        /// <summary>
        /// Test the property 'EmployeeTerritories'
        /// </summary>
        [Test]
        public void EmployeeTerritoriesTest()
        {
            // TODO unit test for the property 'EmployeeTerritories'
        }
        /// <summary>
        /// Test the property 'InverseReportsToNavigation'
        /// </summary>
        [Test]
        public void InverseReportsToNavigationTest()
        {
            // TODO unit test for the property 'InverseReportsToNavigation'
        }
        /// <summary>
        /// Test the property 'Orders'
        /// </summary>
        [Test]
        public void OrdersTest()
        {
            // TODO unit test for the property 'Orders'
        }

    }

}
