/* 
 * ToDo API
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EmployeeTerritories
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmployeeTerritoriesTests
    {
        // TODO uncomment below to declare an instance variable for EmployeeTerritories
        //private EmployeeTerritories instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EmployeeTerritories
            //instance = new EmployeeTerritories();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmployeeTerritories
        /// </summary>
        [Test]
        public void EmployeeTerritoriesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmployeeTerritories
            //Assert.IsInstanceOfType<EmployeeTerritories> (instance, "variable 'instance' is a EmployeeTerritories");
        }


        /// <summary>
        /// Test the property 'EmployeeId'
        /// </summary>
        [Test]
        public void EmployeeIdTest()
        {
            // TODO unit test for the property 'EmployeeId'
        }
        /// <summary>
        /// Test the property 'TerritoryId'
        /// </summary>
        [Test]
        public void TerritoryIdTest()
        {
            // TODO unit test for the property 'TerritoryId'
        }
        /// <summary>
        /// Test the property 'Employee'
        /// </summary>
        [Test]
        public void EmployeeTest()
        {
            // TODO unit test for the property 'Employee'
        }
        /// <summary>
        /// Test the property 'Territory'
        /// </summary>
        [Test]
        public void TerritoryTest()
        {
            // TODO unit test for the property 'Territory'
        }

    }

}
