/* 
 * ToDo API
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Products
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductsTests
    {
        // TODO uncomment below to declare an instance variable for Products
        //private Products instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Products
            //instance = new Products();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Products
        /// </summary>
        [Test]
        public void ProductsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Products
            //Assert.IsInstanceOfType<Products> (instance, "variable 'instance' is a Products");
        }


        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Test]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Test]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }
        /// <summary>
        /// Test the property 'SupplierId'
        /// </summary>
        [Test]
        public void SupplierIdTest()
        {
            // TODO unit test for the property 'SupplierId'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Test]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'QuantityPerUnit'
        /// </summary>
        [Test]
        public void QuantityPerUnitTest()
        {
            // TODO unit test for the property 'QuantityPerUnit'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UnitsInStock'
        /// </summary>
        [Test]
        public void UnitsInStockTest()
        {
            // TODO unit test for the property 'UnitsInStock'
        }
        /// <summary>
        /// Test the property 'UnitsOnOrder'
        /// </summary>
        [Test]
        public void UnitsOnOrderTest()
        {
            // TODO unit test for the property 'UnitsOnOrder'
        }
        /// <summary>
        /// Test the property 'ReorderLevel'
        /// </summary>
        [Test]
        public void ReorderLevelTest()
        {
            // TODO unit test for the property 'ReorderLevel'
        }
        /// <summary>
        /// Test the property 'Discontinued'
        /// </summary>
        [Test]
        public void DiscontinuedTest()
        {
            // TODO unit test for the property 'Discontinued'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Supplier'
        /// </summary>
        [Test]
        public void SupplierTest()
        {
            // TODO unit test for the property 'Supplier'
        }
        /// <summary>
        /// Test the property 'OrderDetails'
        /// </summary>
        [Test]
        public void OrderDetailsTest()
        {
            // TODO unit test for the property 'OrderDetails'
        }

    }

}
