/* 
 * ToDo API
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Territories
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TerritoriesTests
    {
        // TODO uncomment below to declare an instance variable for Territories
        //private Territories instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Territories
            //instance = new Territories();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Territories
        /// </summary>
        [Test]
        public void TerritoriesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Territories
            //Assert.IsInstanceOfType<Territories> (instance, "variable 'instance' is a Territories");
        }


        /// <summary>
        /// Test the property 'TerritoryId'
        /// </summary>
        [Test]
        public void TerritoryIdTest()
        {
            // TODO unit test for the property 'TerritoryId'
        }
        /// <summary>
        /// Test the property 'TerritoryDescription'
        /// </summary>
        [Test]
        public void TerritoryDescriptionTest()
        {
            // TODO unit test for the property 'TerritoryDescription'
        }
        /// <summary>
        /// Test the property 'RegionId'
        /// </summary>
        [Test]
        public void RegionIdTest()
        {
            // TODO unit test for the property 'RegionId'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'EmployeeTerritories'
        /// </summary>
        [Test]
        public void EmployeeTerritoriesTest()
        {
            // TODO unit test for the property 'EmployeeTerritories'
        }

    }

}
